import '../models/product.dart';
import '../models/category.dart';
import '../models/order.dart';
import '../models/scan_item.dart';
import '../models/currency.dart';

class MockDataService {
  MockDataService._();

  static const List<CurrencyInfo> supportedCurrencies = [
    CurrencyInfo(code: 'USD', symbol: '\$', name: 'US Dollar', rateToUsd: 1.0, flagEmoji: '🇺🇸'),
    CurrencyInfo(code: 'NGN', symbol: '₦', name: 'Nigerian Naira', rateToUsd: 1550.0, flagEmoji: '🇳🇬'),
    CurrencyInfo(code: 'EUR', symbol: '€', name: 'Euro', rateToUsd: 0.92, flagEmoji: '🇪🇺'),
    CurrencyInfo(code: 'GBP', symbol: '£', name: 'British Pound', rateToUsd: 0.79, flagEmoji: '🇬🇧'),
    CurrencyInfo(code: 'AED', symbol: 'AED ', name: 'UAE Dirham', rateToUsd: 3.67, flagEmoji: '🇦🇪'),
  ];

  static const List<Category> categories = [
    Category(
      id: 'cat_solid_gold',
      title: 'Solid Gold Masterpieces',
      subtitle: '18K & 24K Hand-Polished Mirror Finish',
      pieceCount: 38,
      startingPriceUsd: 1200,
      imageUrl: 'https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?q=80&w=800&auto=format&fit=crop',
    ),
    Category(
      id: 'cat_diamond_pave',
      title: 'Diamond Pavé & Baguettes',
      subtitle: 'VVS1 Flawless Micro-Prong Settings',
      pieceCount: 52,
      startingPriceUsd: 3400,
      imageUrl: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?q=80&w=800&auto=format&fit=crop',
    ),
    Category(
      id: 'cat_open_face',
      title: 'Open Face & Deep Cut Windows',
      subtitle: 'Architectural Framing & Negative Space',
      pieceCount: 24,
      startingPriceUsd: 1850,
      imageUrl: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?q=80&w=800&auto=format&fit=crop',
    ),
    Category(
      id: 'cat_fangs_caps',
      title: 'Canine Fangs & Single Caps',
      subtitle: 'Subtle Accents & High-Impact Statement Caps',
      pieceCount: 45,
      startingPriceUsd: 650,
      imageUrl: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?q=80&w=800&auto=format&fit=crop',
    ),
    Category(
      id: 'cat_gemstone_opal',
      title: 'Colombian Emerald & Australian Opal',
      subtitle: 'Vibrant Rare Inlays & Custom Stone Mosaics',
      pieceCount: 19,
      startingPriceUsd: 4200,
      imageUrl: 'https://images.unsplash.com/photo-1600003014755-ba31aa59c4b6?q=80&w=800&auto=format&fit=crop',
    ),
    Category(
      id: 'cat_bespoke_3d',
      title: 'Bespoke Atelier Commission',
      subtitle: '1-of-1 Digital CAD Sculpted by Master Jewelers',
      pieceCount: 100,
      startingPriceUsd: 5000,
      imageUrl: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?q=80&w=800&auto=format&fit=crop',
    ),
  ];

  static final List<Product> products = [
    Product(
      id: 'prod_1',
      name: '18K VVS1 Flawless Diamond Cut Top 6',
      subtitle: 'Haute Joaillerie Arch Cap',
      category: 'Diamond Pavé & Baguettes',
      priceUsd: 4850.00,
      priceNgn: 7517500.00,
      rating: 4.98,
      reviewCount: 64,
      purity: '18K Yellow Gold',
      diamondClarity: 'VVS1 Natural',
      imageUrl: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?q=80&w=800&auto=format&fit=crop',
      galleryImages: [
        'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?q=80&w=800&auto=format&fit=crop',
        'https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?q=80&w=800&auto=format&fit=crop',
        'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?q=80&w=800&auto=format&fit=crop',
      ],
      description: 'Handcrafted in our Place Vendôme atelier. Features 420 micro-pave handset VVS1 round brilliant natural diamonds set in lustrous 18K solid yellow gold. Includes digital 3D intraoral scan precision fitting and an armored luxury presentation case.',
      archType: 'Top 6 Arch',
      isFeatured: true,
      isBestSeller: true,
    ),
    Product(
      id: 'prod_2',
      name: 'Place Vendôme Mirror Polish Top 8',
      subtitle: 'Pure Minimalist Solid Gold',
      category: 'Solid Gold Masterpieces',
      priceUsd: 3200.00,
      priceNgn: 4960000.00,
      rating: 4.95,
      reviewCount: 42,
      purity: '24K Yellow Gold',
      diamondClarity: 'N/A (Mirror Gold)',
      imageUrl: 'https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?q=80&w=800&auto=format&fit=crop',
      galleryImages: [
        'https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?q=80&w=800&auto=format&fit=crop',
        'https://images.unsplash.com/photo-1605100804763-247f67b3557e?q=80&w=800&auto=format&fit=crop',
      ],
      description: 'Surgically contoured solid gold arch with an ultra-high gloss mirror finish. Cast using recycled single-origin fine gold, each tooth is micro-beveled for frictionless all-day comfort.',
      archType: 'Top 8 Arch',
      isFeatured: true,
      isBestSeller: false,
    ),
    Product(
      id: 'prod_3',
      name: 'Architectural Open-Face Canine Duo',
      subtitle: 'Subtle Negative Space Frame',
      category: 'Open Face & Deep Cut Windows',
      priceUsd: 1450.00,
      priceNgn: 2247500.00,
      rating: 4.91,
      reviewCount: 29,
      purity: '18K White Gold',
      diamondClarity: 'VS1 Pave Border',
      imageUrl: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?q=80&w=800&auto=format&fit=crop',
      galleryImages: [
        'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?q=80&w=800&auto=format&fit=crop',
      ],
      description: 'Clean architectural framing that highlights natural tooth geometry while bordering the perimeter with micro-pave handset stones in 18K white gold.',
      archType: 'Dual Canine Caps',
      isFeatured: false,
      isBestSeller: true,
    ),
    Product(
      id: 'prod_4',
      name: 'Imperial Emerald & Honeycomb Diamond 16',
      subtitle: 'Museum Quality Masterwork',
      category: 'Colombian Emerald & Australian Opal',
      priceUsd: 18500.00,
      priceNgn: 28675000.00,
      rating: 5.0,
      reviewCount: 18,
      purity: '18K Rose Gold',
      diamondClarity: 'VVS Flawless & Emeralds',
      imageUrl: 'https://images.unsplash.com/photo-1600003014755-ba31aa59c4b6?q=80&w=800&auto=format&fit=crop',
      galleryImages: [
        'https://images.unsplash.com/photo-1600003014755-ba31aa59c4b6?q=80&w=800&auto=format&fit=crop',
      ],
      description: 'Our crown jewel commission. Features certified Colombian vivid green emeralds framed in an 18K rose gold honeycomb diamond setting spanning both upper and lower arches.',
      archType: 'Full 16 Arch',
      isFeatured: true,
      isBestSeller: false,
    ),
    Product(
      id: 'prod_5',
      name: 'Single Diamond Dust Fang Cap',
      subtitle: 'High Precision Solitary Accent',
      category: 'Canine Fangs & Single Caps',
      priceUsd: 780.00,
      priceNgn: 1209000.00,
      rating: 4.88,
      reviewCount: 86,
      purity: '18K Yellow Gold',
      diamondClarity: 'Diamond Dust Stippling',
      imageUrl: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?q=80&w=800&auto=format&fit=crop',
      galleryImages: [
        'https://images.unsplash.com/photo-1605100804763-247f67b3557e?q=80&w=800&auto=format&fit=crop',
      ],
      description: 'A discreet solitary canine piece textured with diamond-point hand stippling for a shimmering, light-refracting matte frost aesthetic.',
      archType: 'Single Canine Cap',
      isFeatured: false,
      isBestSeller: true,
    ),
    Product(
      id: 'prod_6',
      name: 'Platinum 950 Baguette Cut Bridge',
      subtitle: 'Ultra-Dense Industrial Prestige',
      category: 'Diamond Pavé & Baguettes',
      priceUsd: 9200.00,
      priceNgn: 14260000.00,
      rating: 4.97,
      reviewCount: 31,
      purity: '950 Platinum',
      diamondClarity: 'VVS Baguette Diamonds',
      imageUrl: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?q=80&w=800&auto=format&fit=crop',
      galleryImages: [
        'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?q=80&w=800&auto=format&fit=crop',
      ],
      description: 'Precision channel-set calibrated baguette diamonds across heavy solid 950 platinum. Engineered for collectors who accept no compromises.',
      archType: 'Top 6 Arch',
      isFeatured: true,
      isBestSeller: false,
    ),
  ];

  static final List<CommissionOrder> orders = [
    CommissionOrder(
      id: 'ord_1',
      commissionNumber: '#HK-2026-8942',
      date: 'Sept 18, 2026',
      status: 'In Casting & Stone Setting',
      statusBadge: 'STAGE 4/5',
      items: [
        Product(
          id: 'prod_1',
          name: '18K VVS1 Flawless Diamond Cut Top 6',
          category: 'Diamond Pavé',
          priceUsd: 4850.00,
          priceNgn: 7517500.00,
          imageUrl: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?q=80&w=800&auto=format&fit=crop',
          description: 'Handcrafted in Paris atelier.',
        ),
      ],
      totalUsd: 4850.00,
      totalNgn: 7517500.00,
      jewelerName: 'Jean-Luc Atelier (Place Vendôme)',
      trackingNumber: 'HK-SEC-9920194-VAULT',
      estimatedDelivery: 'Oct 02, 2026',
      trackingSteps: [
        TrackingStep(
          title: 'Commission Confirmed & Authenticated',
          description: 'Payment secured via Vault Escrow with 256-bit encryption.',
          timestamp: 'Sept 18, 09:30 AM',
          isCompleted: true,
        ),
        TrackingStep(
          title: '3D Intraoral Scan Approved by DDS',
          description: 'Dr. Adebayo confirmed 99.8% precision dental tolerance.',
          timestamp: 'Sept 19, 02:15 PM',
          isCompleted: true,
        ),
        TrackingStep(
          title: '18K Gold Cast & Tree Assembly',
          description: 'Molten 18K Yellow Gold casted in Paris vacuum chamber.',
          timestamp: 'Sept 20, 11:00 AM',
          isCompleted: true,
        ),
        TrackingStep(
          title: 'Micro-Pave Diamond Setting & Polishing',
          description: 'Master Jeweler currently setting 420 individual VVS stones.',
          timestamp: 'In Progress • Est. Sept 24',
          isCompleted: false,
          isCurrent: true,
        ),
        TrackingStep(
          title: 'Armored Diplomatic Vault Courier Dispatch',
          description: 'Direct temperature-controlled handover to client.',
          timestamp: 'Est. Oct 02',
          isCompleted: false,
        ),
      ],
    ),
    CommissionOrder(
      id: 'ord_2',
      commissionNumber: '#HK-2026-7210',
      date: 'Aug 14, 2026',
      status: 'Delivered & Vault Verified',
      statusBadge: 'COMPLETED',
      items: [
        Product(
          id: 'prod_2',
          name: 'Place Vendôme Mirror Polish Top 8',
          category: 'Solid Gold',
          priceUsd: 3200.00,
          priceNgn: 4960000.00,
          imageUrl: 'https://images.unsplash.com/photo-1617038260897-41a1f14a8ca0?q=80&w=800&auto=format&fit=crop',
          description: 'Pure 24K Yellow Gold solid arch.',
        ),
      ],
      totalUsd: 3200.00,
      totalNgn: 4960000.00,
      jewelerName: 'Henri Rousseau Master Jeweler',
      trackingNumber: 'HK-SEC-6618402-VAULT',
      estimatedDelivery: 'Aug 26, 2026',
      trackingSteps: [
        TrackingStep(
          title: 'Commission Confirmed',
          description: 'Order initiated.',
          timestamp: 'Aug 14',
          isCompleted: true,
        ),
        TrackingStep(
          title: 'Handcrafted & Quality Assayed',
          description: 'Officially hallmarked with French guarantee stamps.',
          timestamp: 'Aug 22',
          isCompleted: true,
        ),
        TrackingStep(
          title: 'Delivered & Fitted in VIP Salon',
          description: 'Client accepted handover in Lagos Penthouse.',
          timestamp: 'Aug 26, 04:00 PM',
          isCompleted: true,
        ),
      ],
    ),
  ];

  static const List<ScanItem> scans = [
    ScanItem(
      id: 'scan_1',
      title: 'Upper Maxillary Arch 3D Scan',
      scanDate: 'Sept 15, 2026',
      verifiedBy: 'Dr. Adebayo DDS (Lagos Clinic)',
      precisionScore: 99.8,
      isUpperArch: true,
      isVerified: true,
      fileSize: '38.4 MB',
    ),
    ScanItem(
      id: 'scan_2',
      title: 'Lower Mandibular Arch 3D Scan',
      scanDate: 'Sept 15, 2026',
      verifiedBy: 'Dr. Adebayo DDS (Lagos Clinic)',
      precisionScore: 99.6,
      isUpperArch: false,
      isVerified: true,
      fileSize: '36.1 MB',
    ),
    ScanItem(
      id: 'scan_3',
      title: 'Legacy Dental Impression Cast',
      scanDate: 'Jan 10, 2025',
      verifiedBy: 'Dr. Laurent Moreau (Paris Atelier)',
      precisionScore: 98.2,
      isUpperArch: true,
      isVerified: true,
      fileSize: '24.0 MB',
    ),
  ];
}
